# ------------------------------------------------------------------------------
# Safety policy file for packages needed for development.
#
# For documentation, see https://docs.pyup.io/docs/safety-20-policy-file
#
# Generally package vulnerabilites listed in the ignore-vulnerabilities
# list below are there because:
# 1. There is no release that resolves the vulnerability.  In this case, there
#    should also be an expire entry to remind the pywbem team to recheck
# 2. The required version of a package to resolve the issue is not available
#    for all of the python version supported by pywbem. In that case, the
#    vulnerability will remain ignored until such time as the versions of
#    python that cannot support the required version of the package are no
#    longer supported by pywbem.

# Configuration for the 'safety check' command
security:

    # Ignore certain severities.
    # A number between 0 and 10, with the following significant values:
    # - 9: ignore all vulnerabilities except CRITICAL severity
    # - 7: ignore all vulnerabilities except CRITICAL & HIGH severity
    # - 4: ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity
    ignore-cvss-severity-below: 0

    # Ignore unknown severities.
    # Should be set to False.
    ignore-cvss-unknown-severity: False

    # List of specific vulnerabilities to ignore.
    # {id}:                 # vulnerability ID
    #     reason: {text}    # optional: Reason for ignoring it. Will be reported in the Safety reports
    #     expires: {date}   # optional: Date when this ignore will expire
    ignore-vulnerabilities:
        37504:
            reason: Fixed Twine version 2.0.0 requires Python>=3.6 and is used there
        39621:
            reason: Fixed pylint version 2.7.0 requires Python>=3.6 and is used there
        40291:
            reason: Fixed pip version 21.1 requires Python>=3.6 and is used there
        42559:
            reason: Fixed pip version 21.1 requires Python>=3.6 and is used there
        45185:
            reason: Fixed pylint version 2.13.0 requires Python>=3.6 and is used there
        51457:
            reason: Py package is no longer being fixed (latest version 1.11.0)
        51499:
            reason: Fixed wheel version 0.38.1 requires Python>=3.7 and is used there
        52495:
            reason: Fixed setuptools version 65.5.1 requires Python>=3.7 and is used there
        61601:
            reason: Fixed urllib3 version 1.26.17 requires Python 2.7 or Python>=3.6 and is used there
        61893:
            reason: Fixed urllib3 version 1.26.18 requires Python 2.7 or Python>=3.6 and is used there
        62044:
            reason: Fixed pip version 23.3 requires Python>=3.7 and is used there
        64227:
            reason: Fixed Jinja2 version 3.1.3 requires Python>=3.7 and is used there
        67599:
            reason: Fixed pip version 21.1 requires Python>=3.6 and is used there
        70612:
            reason: No fixed Jinja2 version

    # Continue with exit code 0 when vulnerabilities are found.
    continue-on-vulnerability-error: False
