---
# Example zhmc_log_forwarder config file

# IP address or hostname of HMC
hmc_host: '10.11.12.13'

# HMC credentials to be used
hmc_user: 'myuser'
hmc_password: 'mypassword'

# Destination for the log entries.
# At this point, only stdout is supported.
dest: stdout

# List of log types to gather:
# * security: HMC Security Log
# * audit: HMC Audit Log
logs: [security, audit]
