# This GitHub workflow will publish the package to Pypi and create a new stable branch when releasing the master branch.
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: publish

on:
  push:  # When pushing a tag
    tags:
    - "*a0"  # Only on tag for a new version

jobs:
  publish:
    name: Try branch creation
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:

    - name: "Create a branch"
      id: create-branch
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/heads/try_branch",
            sha: "${{ github.sha }}",
          })
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Handle HTTP error 422 from creating the branch
      if: steps.create-branch.outputs.status == 422
      run: |
        echo "Error: Creating the branch failed. Create the branch manually:"
        echo "git checkout master"
        echo "git pull"
        echo "git checkout -b try_branch"
        echo "git push --set-upstream origin try_branch"
